version: '3'
services:
  nodereact:
    build:             
        context: .
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /node_modules
    networks:
      - bate_click

networks:
    bate_click:
        driver: bridge
    